const suggestions = [
  "Accident",
  "already applied for loan extension",
  "already extend the loan",
  "Already made full payment yesterday",
  "already made part payment",
  "already paid",
  "Already paid 10000 yesterday, promise to pay something today",
  "Already paid 70000 yesterday. promise to pay the balance",
  "already paid loan",
  "Already paid part yesterday. promise to pay the balance tomorrow",
  "Armed robber, go and look for work to do! stop calling my line!!!",
  "asked for 30k  was given 300k mistakenly, sent mail no response,wont pay until interest is removed.",
  "bank issue",
  "busy",
  "busy number",
  "call back",
  "call back no answer",
  "call back reqested",
  "Call cannot be completed",
  "Call Client back",
  "call drop",
  "call dropped due to network issues",
  "call forwarded",
  "call interrupted by network failure",
  "Cannot be reached",
  "Cannot receive call",
  "claimed  its a fraud",
  "claimed he did not take loan",
  "claimed he did not take the loan from fair money",
  "claimed he didnt take any loan",
  "claimed he extended the loan",
  "claimed he has paid in 113000 plus for his remaining installment payment as promise this morning",
  "claimed her details was use to acess the loan",
  "claimed her FM acct is blocked. waiting for to be  rectifyed",
  "claimed hisacct is not refecting balance after been  autodebited",
  "claimed not to be the right party and doesnt know the right party",
  "claimed she did not take loan",
  "claimed she did not take the loan from fair money",
  "claimed she didnt take any loan",
  "claimed she didnt take any loan but promised to find out who used her details",
  "claimed she has made her payment",
  "claimed she is not the right party and doesnt know the right party",
  "claimed she was declined when she applied",
  "claimed some of his payment is not reflecting inhis balance",
  "claimed the right party is dead but promised to send the obituary when it is available",
  "claimed the right party is indisposed but promised to reach him",
  "claimed the right party is indisposed but reach her",
  "claimed the right party is not but promised to reach her",
  "claimed the right party is not but promised to reach him",
  "claimed to have applied but didnt receive any money",
  "claimed to have paid",
  "claimed to have paid  this afternoonand cleared on the app",
  "claimed to have paid and cleared on the app",
  "client  is on transit ,promise to pay next week",
  "client claims he did not take any loan",
  "client claims he has made his repayment",
  "client claims her part payment did not reflect",
  "client claims it is a wrong number",
  "client claims she did not take any loan",
  'client complain that money was  deducted from his sons acc on 4, but wasn"t deducted from his loan',
  "client complaint made a complain about his loan and unwilling to make payment yet",
  "client did not respond",
  "client doesnt as if he wants to pay",
  "client extended the loan with (5300)",
  "client hung up",
  "client hung up abruptly",
  "client hung up before we conclude the conversation",
  "client hung up before we could conclude",
  "client hung up without no response",
  "client is late",
  "Client is not around",
  "client placed call on hold",
  "Client want to do an extension",
  "client wants to extend his loan",
  "client wants to extend the loan tomorrow",
  "customer already made a loan extension",
  "customer cannot receive call",
  "Customer did an extension",
  "customer didnt collect loan",
  "customer didnt collect loan its a fraudster but several mails have been sent",
  "customer didnt recieve loan and a mail was sent",
  "customer hung up",
  "customer hung up after hearing Fairmoney",
  "Customer Hung up the call",
  "customer is dead",
  "customer is not available",
  "customer line is busy",
  "customer not available",
  "customer not hearing me",
  "customer not picking",
  "customer not reachable",
  "customer not responding",
  "customer not willingly to pay",
  "customer not willingly to pay interest",
  "customer on another call",
  "customer requested that he wants to see a mail from the MD",
  "Customer sole the phone and travelled",
  "customer wants to be autodebted",
  "customer wants to make a loan extension",
  "death of love one",
  "did not apply for loan",
  "did not apply for the loan",
  "did not get the loan",
  "did not pick",
  "did not take a loan",
  "did not take loan",
  "do not call call this number again",
  "dont know fair money. claimed is a newly registered sim",
  "Drop call",
  "Dropped call",
  "extension fee",
  "extention",
  "Family Issues",
  "financial reason",
  "Flashed call",
  "Fraud",
  "hausa speaking agent needed",
  "he applied and paid for extension",
  "he rejected the loan because its small so he didnt recieve the loan and wont pay",
  "he was bereaved",
  "he was defrauded",
  "he was defrauded,he  will extend it on the App",
  "he will extend the loan on the App",
  "his details was used to take the loan without his consent by a fraudster",
  "his wife gave birth",
  "hospitalized",
  "hung up call",
  "hung up call -reception Constraints",
  "hung up suddenly",
  `Hung up, I'm seeing scammer`,
  `I  don't know anyone that bears such a name!`,
  `I did not collect money from Fair money`,
  `I didn't request for a loan but I will do my findings`,
  `I didn't request for this particular loan although I have an account with Fairmoney`,
  `I didn't take loan`,
  `I didn't take loan and I was auto debited twice!!!`,
  `I didn't take loan, I was robbed`,
  "I have problem, promise to pay tomorrow",
  `I lost my phone didn't request for a loan`,
  "I made a loan yesterday, you are not supposed to call me today",
  "I made a mistake and paid the money into a wrong account",
  "I mistakenly sent money into the wrong sterling account",
  "I requested for a loan but not giving",
  "I want to make a loan extension",
  "I want to make a loan extension Friday",
  "I want to make a loan extension today",
  "I want to make a loan extension tomorrow",
  "I was auto debited, promise to pay then hung up",
  `I'm seriously broke but promise to pay`,
  "Just lost her husband but promise to pay something today or tomorrow",
  "Just spoke with your colleague few minutes ago",
  "know nothing about the loan",
  "language barrier",
  "load extended",
  "loan cleared",
  "loan cleared today",
  "loan cleared yesterday",
  "Loan Extention",
  "loan paid and promise to make all the remaining installment payment before the day runs out",
  "loan paid now",
  "loan paid this morning",
  "loan paid, but payment not reflecting",
  "made a  part payment yetserday",
  "Made a part of 10k today, will make another payment next week",
  "made a part payment yesterday",
  "Made a payment of 17k that is not showing on the app",
  "made part payment of  70,000 yesterday",
  "made part payment today",
  "made payment on 18th May and its not reflecting and has sent evidence,will make this month payment",
  "made some payment and it is not reflecting",
  "making a part payment #100000 tomorrow",
  "making a part payment of #100000 today",
  "making a part payment on Friday",
  "making a part payment on Monday",
  "making a part payment on Tuesday",
  "making a part payment this week",
  "making a part payment today",
  "making a part payment today/tomorrow",
  "making a part payment today/tomorrow of #10000",
  "making a part payment tomorrow",
  "making a pat payment today/tomorrow",
  "making payment on friday",
  "making payment on Monday",
  "making payment on Saturday",
  "making payment on sunday",
  "making payment on Thursday",
  "making payment on Wednesday",
  "making payment this weekend",
  "making payment today",
  "making payment today/tomorrow",
  "making payment tomorrow",
  "Medical Expenses",
  "medical reason",
  "Money Paid into the Wrong Account",
  "My husband collected the loan. will let him know",
  "Network failure",
  "no  such number",
  "no answer",
  "no answer to the call",
  "no answern",
  "no plans for payment",
  "no responds",
  `no response from customer's end`,
  "No Responses from customer",
  "no such number",
  "not answering",
  "Not Attempted",
  "Not available",
  "not connecting",
  "not picked up",
  "not reachable",
  `not reachable at the momen't`,
  "not responding",
  "not the right party",
  "not the right party but promised to reach out to the right party",
  "not the right party- promised to relay the  message to the right party",
  "number barred",
  "Number barred from receiving calls",
  "Number Busy",
  "Number can not receive call",
  "number cannot recieve calls",
  "number can't receive calls",
  "number does not exist",
  "number is not valid",
  "On another call",
  "paid 40000 right now but would make another part today or monday",
  "paid loan already",
  "paid loan already and it has cleared on the App",
  "paid loan already before the due dates",
  "paid part payment yesterday",
  "paid part this morning but wants to confirm the possibility paying another today",
  "paid right now",
  "Paid yesterday",
  "part payment made already but promise to make another payment tomorrow",
  "part payment not reflecting but promise to make another payment",
  "pay not reflecting",
  "paying today",
  "payment made already",
  "Payment not Reflecting",
  "Pls stop calling me!!!",
  "promise to make half payment",
  "promise to make part payment",
  "promise to make part payment  and also extend the loan",
  "promise to make part payment ,and client complained that money have been deducted from her acc",
  "promise to make part payment today",
  "promise to make part payment today, and promise to clear all by monday",
  "promise to make part payment today,but complain that the interest / pennalty is much",
  "promise to make part payment tommorrow",
  "Promise to make part payment.",
  "promise to make payment",
  "promise to pay",
  "promise to pay  but someone else use her account to borrow more than her outstanding loan",
  "promise to pay - Loan Extension",
  "promise to pay 50% part payment on or before friday",
  "promise to pay 50% part payment today",
  "promise to pay 50% part payment tomorrow",
  "Promise to pay 50% today",
  "promise to pay part payment today or tomorrow",
  "promise to pay part today",
  "promised to pay today in full",
  "Repayment issue, but promise to renctify and pay on monday",
  "Requested for a call back",
  "Requested for account number",
  "Ringing not picking",
  "Robbery",
  "she was defrauded",
  "she will extend the loan on the App",
  "Sick",
  "sick but promise to make extension tomorrow",
  "sick but promise to pay",
  "sick but promise to pay next week",
  "Sick in hospital",
  "Silent call",
  "slow sale",
  "someone that posed as fairmoney agent used her details to take loan without her consent",
  "someone used his phone to take the loan without his consent",
  "Someone used my details",
  "Someone used my details but I will tell the borrower to pay",
  "Someone used my details, ngucc hung up the call",
  "spoke with a third party",
  "Spoke with a third party but promise the borrower will pay",
  "spoke with a third party who promised to pay",
  "spoke with a third party who said the client is sick",
  "suddenly hung up because of lightdown",
  "switched off",
  "The balance was deducted from my account last weekend.",
  "The borrower had an accident, but promise to pay",
  "The borrower is late",
  "The borrower is serious ill but we will start paying",
  "the client is dead",
  "the client is sick",
  "the full amount was auto debited from my account yesterday",
  "The number dialed is invalid",
  "The number dialed is not valid",
  "third party",
  "third party to relay the message",
  "third party, medical reason",
  "unable to make call to this number",
  "unwilling client",
  "Unwilling Customer",
  "unwilling customer to pay",
  "unwilling to committe",
  "unwilling to pay",
  "Unwilling to pay loan balance",
  "voice call",
  "want a call back",
  "wants a call back",
  "wants account number",
  "wants account number,hung up suddenly",
  "wants his acct to be  reconcile so he can balance up his payment",
  "wants to be called back",
  "wants to extend  the loan",
  "wants to extend the loan",
  "wants to renegotiate payment",
  "war",
  "will ask her daughter if she used her details to take loan",
  "will talk to customer to pay",
  "will tell the person that used her details to take loan",
  "will tell the right party",
  "Will try and make a payment",
  "willing to pay",
  "wish to apply for loan extension",
  "Wrong number",
  "Wrong outstanding balance, but promise to pay 60000 tomorrow",
  "Wrong outstanding balance, but promise to pay something in the next 2 days",
  "Wrong outstanding balance, I paid 50000 last week but promise to pay something today or tomorrow",
  "yoruba",
  "Yoruba client",
];
export default suggestions;
